### ISSUE TITLE
require() of ES Module not supported.

### ISSUE THREAD

**Issue by KeJunMao** [uni-helper/vite-plugin-uni-pages#62]
### 描述问题

```
pnpm dev:h5

> playground@0.1.1 dev:h5 D:\workspace\uni-helper\vite-plugin-uni-pages\packages\playground
> uni

请注意运行模式下，因日志输出、sourcemap 以及未压缩源码等原因，性能和包体积，均不及发行模式。
正在编译中...
failed to load config from D:\workspace\uni-helper\vite-plugin-uni-pages\packages\playground\vite.config.ts
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\workspace\uni-helper\vite-plugin-uni-pages\node_modules\.pnpm\lodash-es@4.17.21\node_modules\lodash-es\lodash.js from D:\workspace\uni-helper\vite-plugin-uni-pages\packages\core\dist\index.cjs not supported.
Instead change the require of lodash.js in D:\workspace\uni-helper\vite-plugin-uni-pages\packages\core\dist\index.cjs to 
a dynamic import() which is available in all CommonJS modules.
    at Object._require.extensions.<computed> [as .js] (file:///D:/workspace/uni-helper/vite-plugin-uni-pages/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62080:17)
    at Object.<anonymous> (D:\workspace\uni-helper\vite-plugin-uni-pages\packages\core\dist\index.cjs:11:18)
    at Object._require.extensions.<computed> [as .js] (file:///D:/workspace/uni-helper/vite-plugin-uni-pages/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62080:17)
    at Object.<anonymous> (D:\workspace\uni-helper\vite-plugin-uni-pages\packages\playground\vite.config.ts:34:44)       
    at Object._require.extensions.<computed> [as .js] (file:///D:/workspace/uni-helper/vite-plugin-uni-pages/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62077:24)
    at loadConfigFromBundledFile (file:///D:/workspace/uni-helper/vite-plugin-uni-pages/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62085:21)
    at loadConfigFromFile (file:///D:/workspace/uni-helper/vite-plugin-uni-pages/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:61943:34)
    at async resolveConfig (file:///D:/workspace/uni-helper/vite-plugin-uni-pages/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:61564:28)
    at async Module.createServer (file:///D:/workspace/uni-helper/vite-plugin-uni-pages/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:60884:20)
    at async createServer (D:\workspace\uni-helper\vite-plugin-uni-pages\node_modules\.pnpm\@dcloudio+vite-plugin-uni@3.0.0-alpha-3061620221230002_gioipz73x7e6odstk4bwyk6buq\node_modules\@dcloudio\vite-plugin-uni\dist\cli\server.js:44:20)    
    at async CAC.runDev (D:\workspace\uni-helper\vite-plugin-uni-pages\node_modules\.pnpm\@dcloudio+vite-plugin-uni@3.0.0-alpha-3061620221230002_gioipz73x7e6odstk4bwyk6buq\node_modules\@dcloudio\vite-plugin-uni\dist\cli\action.js:45:28)      
 ELIFECYCLE  Command failed with exit code 1.
```

### 复现

pass

### 系统信息

```Shell
pass
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
试着改用 lodash-unified

**Comment by KeJunMao** [comment]
直接替换为lodash了
